### ISSUE TITLE
How to setup this docker image with MariaDB5 MySQL on Synology?

### ISSUE THREAD

**Issue by BobWs** [ckulka/baikal-docker#10]
Do you have a tutorial how to setup baikal docker with MariaDB 5 on Synology docker?
I'm getting this error:
 Validation error
Baïkal was not able to establish a connexion to the MySQL database as configured.
MySQL says: could not find driver

**Comment by ckulka** [comment]
Thanks @BobWs, I'm able to replicate this issue... shouldn't be much of an issue though, looking into it.

**Comment by ckulka** [comment]
Reopening to verify this solves the issue, will close when it's available as non-experimental image variant

**Comment by BobWs** [comment]
So which image should I use to test baikal with MySQL? I’m on docker synology.

**Comment by BobWs** [comment]
I see you have only altered the nginx inmage, right? I am using the Apache version
Is it possible to also at support for Apache

**Comment by BobWs** [comment]
I've tested experimental, experimental-nginx, experimental-apache non is working with MySQL

**Comment by ckulka** [comment]
I ran into an issue building the multi-arch images, `experimental-nginx-amd64` should work. I'll see to build the multi arch and arm variant over the weekend.

**Comment by ckulka** [comment]
Hi @BobWs , just finished the ARM build for nginx and updated the multi-arch tag `experimental-nginx` - could you please give it a try? I'll look into the missing package(s) for the Apache variant next.

**Comment by BobWs** [comment]
So I've tested the multi arch `experimental-nginx` but it isn't working. Getting the "Validation error
Baïkal was not able to establish a connexion to the MySQL database as configured.
MySQL says: could not find driver "

After that to verify if my setup was good I downloaded `experimental-nginx-amd64` and tested it with mariadb 5 and no error and I could setup accounts and the database was working fine.
I also tested this image https://github.com/binfalse/Baikal and this one is also working with mariadb 10 and 5.

If you need more info let my know. Or maybe to test another build, preferable Apache

**Comment by ckulka** [comment]
Sorry, had a typo in my build script... `experimental-nginx` should now work, just tested it and it works with both MariaDB 5 and 10 (same dependency that needed to be installed). I'll look into Apache next.

**Comment by ckulka** [comment]
So, this was easier than expected. Can you please give `experimental-nginx` and `experimental-apache` a try?

**Comment by BobWs** [comment]
I will give them a try

**Comment by BobWs** [comment]
So I have tested both images `experimental-nginx` and `experimental-apache` and they both work with mariadb. Didn't tested them with mariadb 10 but I sure it won't be  problem.

`experimental-nginx` was a bit of a problem connecting with my IOS/macOS Calendar `.well-known` wasn't working. 

`experimental-apache` was working fine! Could login from both IOS and macOS Calendar. And the SSL didn't give any problem with my own domain SSL. 

I am only wondering how to change the settings in 000-default.conf
`	SSLEngine on
	SSLCertificateFile /etc/ssl/private/cert.pem
	SSLCertificateKeyFile /etc/ssl/private/privkey.pem`
I had changed the `baikal.public.pem` to `cert.pem` and `baikal.private.pem` to `privkey.pem`
manually through WinSCP.

But isn't there another way to do that?

**Comment by ckulka** [comment]
Can you share your `docker-compose.yml` (or anything else where you configure your container)? I think the easiest way would be to adjust the volume mount (effectively renames the file in the container).

**Comment by BobWs** [comment]
Okay, so I just tried again to upload some screen-shot of my Synology docker GUI setup but I keep getting an error that the upload didn't succeed. 

So I have write down my steps in the docker GUI to setup the Baikal container with Mariadb. I hope you understand it :-)

### **Setup Mariadb 5 or 10**

**Create folder in Volume1/docker**
`docker/mariadb/databases`

`container_name: mariadb`

**Mount volumes:**
`docker/mariadb/databases:/var/lib/mysql`

**Port settings:**
`3307:3306`
        
**ENVIRONMENT:**
`MYSQL_ROOT_PASSWORD:[STRONG-PASSWORD]`
`MYSQL_DATABASE: baikal`
`MYSQL_USER: baikal`
`MYSQL_PASSWORD: [STRONG-PASSWORD]`

### **Setup Baikal**

**Create folders in volume1/docker**
`volume1/docker/baikal/ssl`
	`../docker/baikal/specific`
	`../docker/baikal/specific/db (when setup with sqlite3)`
	` ../docker/baikal/sites-available`

**SSL CERT files:**
`copy SSL CERT to: volume1/docker/baikal/ssl`

`copy file 000-default.conf to: ../docker/baikal/sites-available`
`change settings in file: SSLCertificateFile /etc/ssl/private/cert.pem`
				  			`SSLCertificateKeyFile /etc/ssl/private/privkey.pem`


### **Setup Baikal Container**
**Launch Container:**
`container_name: baikal`

**Mount volumes:**
`docker/baikal/ssl : /etc/ssl/private`
`docker/baikal/specific : /var/www/baikal/Specific`
`docker/baikal/specific/db : /var/www/baikal/Specific/db (when setup with sqlite3)`
`docker/baikal/sites-available : /etc/apache2/sites-available`

**Port settings:**
`8443:443`
`8008:80`

**links:	(alias)**
`mariadb : baikal-db`

**ENVIRONMENT: (at the following variable and value)**
`BAIKAL_SERVERALIAS: [my.domain.com]`
`BAIKAL_SERVERNAME: [my.domain.com]`
`SSLCertificateFile: cert.pem`
`SSLCertificateKeyFile: privkey.pem`

**Start the mariadb and baikal containers**

With these GUI setup steps the baikal and mariadb works fine and I can connect to the calendars and contact via IOS/macOS apps.

I don't know how to use the `docker-compose.yml` in synology. I'm new to docker. Still learning;-)

If you have any suggestions how to smooth the setup/installation I would like to hear from you.

**Comment by BobWs** [comment]
Hi, when do you expect to update the non-experimental image variants with mariadb support?
I've been testing the experimental-apache version the past week and is working great, didn't see any bugs so far.

**Comment by ckulka** [comment]
Sorry took so long, I'll see to merge it today/tomorrow.

**Comment by ckulka** [comment]
Hi @BobWs, regarding the certificates, in addition to mounting folders, can you also mount files?

With regular `docker-compose.yml` files and `docker run`, it's possible to mount a file into the container under a different name, basically renaming it inside the container.

Based on https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.apache.yaml#L15, it should look something like this:

```yaml
services:
  baikal:
    image: ckulka/baikal:apache
    volumes:
      - baikal:/var/www/baikal/Specific
      - volume1/docker/baikal/ssl/cert.pem:/etc/ssl/private/baikal.public.pem
      - volume1/docker/baikal/ssl/privkey.pem:/etc/ssl/private/baikal.private.pem
```

I'm not sure if Synology can do this, but could you please try to replace your volume mount for the SSL folder with two file mounts, one for each certificate file, using a different target name?

**Comment by ckulka** [comment]
Finally got to update the `0.4.6` tags - if things run as expected on your end, I'll close this issue.

**Comment by BobWs** [comment]
no worries, I will give it a try and let you know.

**Comment by BobWs** [comment]
The Apache 0.4.6 is working with mariadb without any problems. I've have tested this version and everything is working fine for me. This issue can be closed. Thanks!

**Comment by ckulka** [comment]
Good to hear, have fun

/close

**Comment by jodumont** [comment]
@ckulka 
mysql also works with nginx experimental
I'm not using a synology
but I had the same `MySQL says: could not find driver` error 
with both latest apache and nginx
