### ISSUE TITLE
Issue: Getting redirected to localhost

### ISSUE THREAD

**Issue by merspieler** [ckulka/baikal-docker#101]
I'm trying to run baikal behind an apache2 reverse proxy which handles TLS.
When I access my public url, I get the page but some links reference localhost so I've gotta edit the url to get there.
My service lives under baikal.<my.domain>, the container is started with -p 8085:80, and the links then point to localhost:8085.
I've tried the normal, apache and nginx 0.9.2 images, all with the same behavior.
I've set the BAIKAL_SERVERNAME env var to baikal.<my.domain>

Do I need to do to get rid of that problem?

**Comment by ckulka** [comment]
Hi @merspieler, can you show me the Apache2 httpd configuration file with the reverse proxy directives to the Baikal container?

**Comment by ckulka** [comment]
Thanks - according to the [ProxyPassReverse Directive](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypassreverse) docs, you're missing directives to rewrite the HTML content:

> To rewrite HTML content to match the proxy, you must load and enable [mod_proxy_html](https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html).

* [ProxyHTMLEnable Directive](https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html#proxyhtmlenable)
* [ProxyHTMLURLMap Directive](https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html#proxyhtmlurlmap)
* [ProxyHTMLExtended Directive](https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html#proxyhtmlextended)

I haven't tried it with an example yet, but I'd imagine it'd be something along these lines:

```conf
ProxyHTMLEnable On
ProxyHTMLExtended On
ProxyHTMLURLMap http://localhost:8085/ /
```

Hope this helps 👍
