### ISSUE TITLE
When try to edit a Calendar via WebAdmin I get this error in the browser!

### ISSUE THREAD

**Issue by BobWs** [ckulka/baikal-docker#103]
Hi,
When I try to edit a Calendar via WebAdmin I get the following error in the browser! I doesn't happen to all the Calendars, with some users calendars it is working and I can Edit it, but some users default calendars can not be edit.

Do you know how to fix this?

![edit button](https://user-images.githubusercontent.com/5485820/204820261-4b47a6ab-28a7-4702-9ef6-af2419574ff1.png)

```
ErrorException: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/baikal/Core/Frameworks/Formal/Element/Text.php:69
Stack trace:
#0 [internal function]: Baikal\Framework::exception_error_handler(8192, 'htmlspecialchar...', '/var/www/baikal...', 69)
#1 /var/www/baikal/Core/Frameworks/Formal/Element/Text.php(69): htmlspecialchars(NULL)
#2 /var/www/baikal/Core/Frameworks/Formal/Form.php(354): Formal\Element\Text->render()
#3 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/User/Calendars.php(82): Formal\Form->render()
#4 /var/www/baikal/Core/Frameworks/Flake/Core/Render/Container.php(69): BaikalAdmin\Controller\User\Calendars->render()
#5 /var/www/baikal/Core/Frameworks/Flake/Controller/Page.php(90): Flake\Core\Render\Container->renderBlocks()
#6 /var/www/baikal/html/admin/index.php(90): Flake\Controller\Page->render()
#7 {main}

```

**Comment by ckulka** [comment]
Hi @BobWs, according to the diff of the 0.9.3 release, it might have been fixed: https://github.com/sabre-io/Baikal/compare/0.9.2...0.9.3#diff-cfa1f17fd08db31bb6a07e0e483b5b9386bdac7f065109182c291146388948bc

Let me know if they really did, hope it works out 👍

**Comment by BobWs** [comment]
> Let me know if they really did, hope it works out 👍

It’s fixed! The update fixed my problem!
