### ISSUE TITLE
After upgrade from 0.9.2, cannto start container

### ISSUE THREAD

**Issue by MichiFr** [ckulka/baikal-docker#114]
Hi!

Just upgraded from previous version 0.9.2 on my Synology NAS, using Portainer for upgrading, to the new version 0.9.3. However, the new container does not start and exits with error:

_sh: 0: cannot open /opt/start.sh: No such file_

I've used Portainer's _recreate_ feature with option _pull latest image_ option, as for any container before.

**Comment by ckulka** [comment]
Yes, the custom commands wasn't required anymore. Out of curiosity, is there a way to **not** specify a command and just use the image's default command?
