### ISSUE TITLE
mail server with unraid install

### ISSUE THREAD

**Issue by jp8311** [ckulka/baikal-docker#120]
Hi all
I'm feeling a bit thick but I can't quite get my head around how to enable sharing of calendars when the docker is installed on unraid

I'm trying to reconcile the instructions here: https://github.com/ckulka/baikal-docker/blob/master/docs/email-guide.md having used these https://github.com/ckulka/baikal-docker/blob/master/docs/unraid-installation-guide.md

I feel like it should be under the 'extra parameters' in the docker image but I'm at a loss for how to format it.

Any guidance would be appreciated

**Comment by ckulka** [comment]
Spring cleaning: Hi @jp8311, I'd imagine you have solved this already, but just in case or for others:

I don't have Unraid myself, so this might be off, but it should not be an "extra parameter", but instead an environment variable. Edit the container, click "Add another port, path or variable" at the bottom, choose variable from the dropdown, set the key to "MSMTP" and value to your MSMTP configuration based on https://github.com/ckulka/baikal-docker/blob/master/docs/email-guide.md.

Reference: https://www.reddit.com/r/unRAID/comments/ymqr5y/comment/iv5c5tm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Hope this helps!
