### ISSUE TITLE
nginx port is fixed at 80 inside container

### ISSUE THREAD

**Issue by feihe-Chicago** [ckulka/baikal-docker#122]
because my 80 port inside the docker has been taken, I was trying to run baikal at a different port:

    ports:
      - "8001:8001"

When container is up and running, fire up browser http://localhost:8001, the webpage never loads. I went into the container and checked the nginx default.conf file, and found that the nginx server setup listening port:80. Is this a problem? Can we change this so that the listening port can be configured as expected?

Thanks

**Comment by nillebor** [comment]
8001 is not the correct port. The Baikal port is 80. If you want to have the container on another port, you have to map to this one: 8001:80.

For the rest, you can use a reverse proxy. This also makes an SSL encrypted connection possible.

**Comment by dnielso5** [comment]
the reasoning is the first number is the external port and the second one is the docker internal port.

**Comment by jmnicolas90** [comment]
The problem with internal ports less than 1000 is that the image can't be run in Podman rootless. It would be nice if the internal port could be set up in an ENV variable.

**Comment by ckulka** [comment]
Spring cleaning, closing this issue given the answers above should have addressed the issue. Thank you @nillebor and @dnielso5!
