### ISSUE TITLE
VFREEBUSY does not work

### ISSUE THREAD

**Issue by switux** [ckulka/baikal-docker#125]
Hello

Just installed the latest image (nginx variant) and I get the following errors in the log anytime I change the date in thunderbird (102.14.0) with lightning:

192.168.200.123 - test [25/Aug/2023:14:52:02 +0000] "POST /dav.php/calendars/test/outbox/ HTTP/1.1" 200 491 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Thunderbird/102.14.0" "-"
2023/08/25 14:52:02 [error] 48#48: *61 FastCGI sent in stderr: "PHP message: Sabre\VObject\ParseException: This parser only supports VCARD and VCALENDAR files in /var/www/baikal/vendor/sabre/vobject/lib/Parser/MimeDir.php:163
Stack trace:
#0 /var/www/baikal/vendor/sabre/vobject/lib/Parser/MimeDir.php(90): Sabre\VObject\Parser\MimeDir->parseDocument()
#1 /var/www/baikal/vendor/sabre/vobject/lib/Reader.php(47): Sabre\VObject\Parser\MimeDir->parse()
#2 /var/www/baikal/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(895): Sabre\VObject\Reader::read()
#3 /var/www/baikal/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(777): Sabre\CalDAV\Schedule\Plugin->getFreeBusyForEmail()
#4 /var/www/baikal/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(726): Sabre\CalDAV\Schedule\Plugin->handleFreeBusyRequest()
#5 /var/www/baikal/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(182): Sabre\CalDAV\Schedule\Plugin->outboxRequest()
#6 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CalDAV\Schedule\Plugin->httpPost()
#7 /var/www/baikal/vendor/sabre/dav/lib" while reading response header from upstream, client: 192.168.200.123, server: _, request: "POST /dav.php/calendars/test/outbox/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.200.21:9666"

The request being:

BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
METHOD:REQUEST
BEGIN:VFREEBUSY
UID:a34f0d14-5e23-41e7-b5d6-54a5f654f726
DTSTAMP:20230825T145128Z
DTSTART;VALUE=DATE:20230902
DTEND;VALUE=DATE:20230918
ORGANIZER:mailto:(snip)
ATTENDEE;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVIDUAL:mailt
 o:(snip)
END:VFREEBUSY
END:VCALENDAR

The response is:

<?xml version="1.0" encoding="utf-8"?>
<cal:schedule-response xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav">
  <cal:response>
    <cal:recipient>
      <d:href>mailto:(snip)</d:href>
    </cal:recipient>
    <cal:request-status>3.7;No calendar-home-set property found</cal:request-status>
  </cal:response>
</cal:schedule-response>

It is an out of the box install with a couple of users added.

I have read a few threads about VFREEBUSY in baikal, I have changed TZ to UTC (I have seen this could be a pb if set to something else).

Thanks for your support,
F.L

**Comment by ckulka** [comment]
Hi @switux , this looks like an error with Baikal itself, not the Docker container. I'd open an issue over at https://github.com/sabre-io/Baikal, since they're familiar with the code itself and hopefully can help.

Opening an issue repository https://github.com/sabre-io/vobjectmight be even better, given [`MimeDir.php`](https://github.com/sabre-io/vobject/blob/master/lib/Parser/MimeDir.php) (where the error is being thrown) comes form there.
