### ISSUE TITLE
Sharing Plugin

### ISSUE THREAD

**Issue by Medic-2016** [ckulka/baikal-docker#128]
I'm needing to add the sharing plugin to my Baikal instance on Docker. I have it installed through the CLI commands on the official docs. Any ideas on how to make this work?

**Comment by ckulka** [comment]
Hi @Medic-2016 , if you mean this https://sabre.io/dav/caldav-sharing/ plugin, then imho the easiest way to enable it would be similar to https://github.com/ckulka/baikal-docker/issues/97#issuecomment-1279801363:

1. Create a shell script file `50-add-sharing-plugin.sh file`

  ```sh
  cat <<EOT >> /var/www/baikal/Core/Frameworks/Baikal/Core/Server.php
  
  // Enable CalDAV Sharing plugin, see https://sabre.io/dav/caldav-sharing/
  $server->addPlugin(new Sabre\DAV\Sharing\Plugin());
  $server->addPlugin(new Sabre\CalDAV\SharingPlugin());
  EOT
  ```

2. Mount this file into the container as `/docker-entrypoint.d/50-add-sharing-plugin.sh`

Hope this helps!

**Comment by rpoovey** [comment]
I am not sure at what point this happened, but it seems like the `server` variable is now a protected variable and this method needs some adjustment to work. The new file I am using is: 
```bash 
cat <<EOT >> /var/www/baikal/Core/Frameworks/Baikal/Core/Server.php

// Enable CalDAV Sharing plugin, see https://sabre.io/dav/caldav-sharing/
\$server = new \Sabre\DAV\Server($tree);
\$server->addPlugin(new \Sabre\DAV\Sharing\Plugin());
\$server->addPlugin(new \Sabre\CalDAV\SharingPlugin());
EOT
```
Also, note, the `\` before `Sabre` seems to be required. I am not well versed in PHP so someone may have a more elegant solution.
