### ISSUE TITLE
New release to mainline msmtp support?

### ISSUE THREAD

**Issue by eanmclaughlin** [ckulka/baikal-docker#131]
I just spent... a while troubleshooting why I wasn't getting email output following the email example before I realized that `msmtp` isn't even installed on the current main releases and before I scrolled all the way to the bottom of https://github.com/ckulka/baikal-docker/discussions/61. 

I think based on the comments in that thread over the past year indicating things working successfully in the experimental images with msmtp that it's safe to create a new release.

**Comment by ckulka** [comment]
Hi @eanmclaughlin , fair point - I'll release that very soon. Currently packing up for vacation, but it'll be there within the next few days.

**Comment by ckulka** [comment]
Closed by release [0.9.3+msmtp](https://github.com/ckulka/baikal-docker/releases/tag/0.9.3%2Bmsmtp)
