### ISSUE TITLE
Release version 0.9.4

### ISSUE THREAD

**Issue by ckulka** [ckulka/baikal-docker#133]
Creating this one for myself and to let others know: Release 0.9.4 is coming, I aim to publish it later this week.

**Comment by pako88** [comment]
Hi @ckulka ,
I can't find 0.9.4 in Releases [0] and also not tagged in Docker Hub [1].
Is it still planned to tag the v0.9.4 accordingly?

[0] https://github.com/ckulka/baikal-docker/releases
[1] https://hub.docker.com/r/ckulka/baikal/tags

**Comment by ckulka** [comment]
Hi @pako88, I hadn't created a release for it yet, this issue was closed automatically since the PR was merged.

But it's building & publishing now, should be there shortly: <https://github.com/ckulka/baikal-docker/actions/runs/7253667046>

**Comment by pako88** [comment]
Thanks for the clarification!
