### ISSUE TITLE
Allow skipping run of `/docker-entrypoint.d/40-fix-baikal-file-permissions.sh`

### ISSUE THREAD

**Issue by sethidden** [ckulka/baikal-docker#134]
Hey,
Your image is used in the TrueCharts helm chart repository for TrueNAS. It's used to basically have a point and click installation of Baikal. See https://truecharts.org/charts/incubator/baikal/

I've noticed an issue with the image and described my observations and a workaround here: https://tagisow.dev/2023-11-21-running-the-truecharts-baikal-chart.html

I take it that this is the same issue as https://github.com/docker/for-linux/issues/388

Could you please add a SKIP_CHOWN environment variable, that if set, would skip running `40-fix-baikal-file-permissions.sh`? This would allow the container to respond to a Kubernetes health check in a timely manner.

Alternatively, it may be just easier to publish a new tag like `baikal-docker:nginx-raw` where `40-fix-baikal-file-permissions.sh` is completely missing from the image.

**Comment by ckulka** [comment]
Not yet published, I hope to get that out to Docker Hub this weekend 👍
