### ISSUE TITLE
Cannot send emails with 9.3.0

### ISSUE THREAD

**Issue by Judman** [ckulka/baikal-docker#135]
I might be dense, but I cannot get an invite to send via email. I have test msmtp and it will send an email out through my hosted mailbox, but when I add a calendar event with an added participant the invite never arrives. Is there a Baikal or sabre/dav log location I should be checking. Sorry for the entry level questions. I know just enough to get myself in trouble.

Below are my configs with sensitive details replaced with example data.

cat /etc/msmtprc

defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
account        default
host           hosted.example.org
port           587
from           calendar@example.org
user           calendar@example.org
password       **password**

echo "This is a test e-mail from my server using msmtp!" | msmtp mailto:email@example.com

Result:
Nov 07 04:18:46 host=hosted.example.org tls=on auth=on user=[calendar@example.org](mailto:calendar@example.org) from=[calendar@example.org](mailto:calendar@example.org) recipients=[email@example.com](mailto:email@example.com) mailsize=181 smtpstatus=250 smtpmsg='250 2.0.0 Ok: queued as DF8845C04F0' exitcode=EX_OK

**Comment by thomasjanker** [comment]
I got the same issue with 9.3.0. Before, I used an older experimental and it worked perfectly.

After activating logging for msmtp by adding "logfile /tmp/msmtp.log" to the environment variables, no lines appear for mails that should have been sent by baikal. Those sent on the shell do appear.

**Comment by thomasjanker** [comment]
This PR fixes the mail issue on my side: https://github.com/ckulka/baikal-docker/pull/142

**Comment by Judman** [comment]
Thanks for following back up on this! I breifly looked at how to pull an older image to test, but had to move on to other things before i could figure it out. Hopefully i can try to look at this again.

**Comment by Judman** [comment]
> This PR fixes the mail issue on my side: #142

This fix did it for me on 0.9.3!

**Comment by ckulka** [comment]
@Judman this should be fixed in the experimental image variants now.

I hope to re-publish a working 0.9.4 soon, I want to verify though first if I can make it a little more secure, limiting read-access to the `/etc/msmtprc` file to only the `msmtp` group.

**Comment by ckulka** [comment]
Hi @Judman , I just re-released the latest version 0.9.4 where msmtp should now work: https://github.com/ckulka/baikal-docker/releases/tag/0.9.4%2Bmsmtpfix

**Comment by Judman** [comment]
> Hi @Judman , I just re-released the latest version 0.9.4 where msmtp should now work: https://github.com/ckulka/baikal-docker/releases/tag/0.9.4%2Bmsmtpfix

I pulled 0.9.4 and it worked no problem! Many thanks!
