### ISSUE TITLE
Can you update baikal image to 0.5.2

### ISSUE THREAD

**Issue by BobWs** [ckulka/baikal-docker#14]
Baikal is maintained again can you please update you baikal-image to the latest version?
https://github.com/sabre-io/Baikal/releases

Thanks

**Comment by ckulka** [comment]
Hi @BobWs,
sorry for the delay -  I've upgraded to Baikal 0.5.2 and will upgrade to 0.5.3 in a moment - the builds on Docker Hub take a while though (10 minutes per image, each new release version are 12-18 images), so it might take a couple of hours before they are available.

**Comment by ckulka** [comment]
Ok... turns out PHP 7.3 has a breaking change from PHP 7.2 (found out as I was testing #16).

Long story short, images for 0.5.1, 0.5.2 and 0.5.3 are rebuilding and it'll take a few hours again.

**Comment by BobWs** [comment]
Hi thanks for the update. I will give it a test-spin and report any issues
