### ISSUE TITLE
Bug in the apache tag

### ISSUE THREAD

**Issue by BobWs** [ckulka/baikal-docker#15]
there is still a bug in the `apache:apache` and `apache:latest` tags. The driver problem when using mariadb. The only `apache` version which is working at the moment is `0.4.6-apache`

**Comment by ckulka** [comment]
Hi @BobWs ,

once the new `ckulka/baikal:apache` and `ckulka/baikal:latest` images are build (in about 4h), the mariadb issues should be resolved. I've just tested it locally here and the driver issues are gone.

This probably came from outdated references in the multi-arch manifests, an issue that's now finally resolved by completely automating the build process on Docker Hub for all architectures.

**Comment by BobWs** [comment]
Hi thanks for the update

**Comment by ckulka** [comment]
Closing this issue as the images have all been built and are available
