### ISSUE TITLE
Accessing cal.php leads to: Error: Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by andyvk85** [ckulka/baikal-docker#16]
Hi ckulka,

I try to use the stable release 0.4.6 but I face a problem when I want to access "http://127.0.0.1/cal.php/calendars/testuser/default".

**The following error occurs:**
Error: Class 'DOMDocument' not found in /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php:256
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/Server.php(123): Sabre\DAV\Server->exec()
#1 /var/www/baikal/html/cal.php(65): Baikal\Core\Server->start()
#2 {main}

**After searching for a solution I found that:**
https://github.com/sabre-io/Baikal/issues/701

Honestly, I don't know if this could fix it? Does someone can repeat my error?

**Comment by ckulka** [comment]
Hi @andyvk85 ,

sorry for the delay - seems like the image was missing the XML extension, which the newer images (building right now) have.

They're available in a few of hours once Docker Hub is done building them (see #14), then it should work.

**Comment by ckulka** [comment]
Closing this issue as the images are all built
