### ISSUE TITLE
Question: Does baikal support memos for iphone?

### ISSUE THREAD

**Issue by yusyel** [ckulka/baikal-docker#165]
Calendar and reminders shows up but notes doesn't. Does it support?

Also reminders one list for per user? Can I use more then one for 1 user?

**Comment by ckulka** [comment]
That's a good question for [sabre-io/Baikal](https://github.com/sabre-io/Baikal/issues), since that's where the code maintainers for Baikal are - this repository just provides the container image, sorry.
