### ISSUE TITLE
Access via reverse proxy by non standard 443 port

### ISSUE THREAD

**Issue by acotor** [ckulka/baikal-docker#169]
Hi, I set up a baikal:nginx container and it works on my LAN, but something wrong happens when I reverse proxy (using Nginx Proxy Manager) it to a none standard port on a dav.mydomian.

When I access `https://dav.mydomain:9443`, html texts are loaded, but css/js/png failed to load. I checked the console, css/js/png are requested via `https://dav.mydomain/res/***` , which missed the port 9443. The Login button on page is linked to `https://dav.mydomain/admin`, which missed the 9443 too.

NPM side, I set a Proxy Hosts

- Details Tab, Domain Names is `dav.mydomian`; Scheme / Forward Hostname IP/ Forward Port are `http` / `127.0.0.1` / `5130`
- SSL Tab, Set.
- Advanced Tab, `listen [::]:9443 ssl http2;` `listen 9443 ssl http2;`

How can I solve this problem, or dig in more about the reason?

Thanks !

Port 5130 on localhost is mapping to the port 80 on the baikal:nginx container.

**Comment by ckulka** [comment]
I did some local testing, can you try setting the `Host` HTTP header to `dav.mydomain:9443`?

Not sure why `X-Forwarded-Port` and `X-Forwarded-Host` are not used, but setting the `Host` header should fix your issue.

**Comment by joshhansen** [comment]
I ran into what seems to be the same issue on 0.11.1. Setting the Header to explicitly include the non-standard port made no difference. Switching back to the standard port 443 makes everything work perfectly. The admin application code seems likely to be at fault, not the HTTP server configuration.

**Comment by joshhansen** [comment]
Update: the same problem persists in 0.12.0
