### ISSUE TITLE
Upgrade baikal docker without data loss

### ISSUE THREAD

**Issue by emilevandeven** [ckulka/baikal-docker#170]
I use portainer / docker / watchtower to keep my systems up-to-date. In the past I included my baikal docker, but it seems that the automatic update doesn't work because it uses another volume for the data. So after update the database was empty. The old volume was still available so I was able to correct this.
Is there a way to use automatic update with watchtower without the problem I mentioned above?

**Comment by Vysp3r** [comment]
I think if you use persistent data instead of volumes it will fix your problem.

**Comment by emilevandeven** [comment]
Excuse me for the late response! @Vysp3r thanks for the suggestion! That's the solution for my problem.
