### ISSUE TITLE
New release 0.9.5

### ISSUE THREAD

**Issue by tanrak** [ckulka/baikal-docker#173]
Hi, there is a new release of Baikal available.

**Comment by ckulka** [comment]
I would like to give PHP 8.2 a try - @tanrak are you available for testing it a bit more thoroughly? My automated tests really only cover the initial setup until now.

If not, then I'll just keep 8.1 until I found a way to do more extensive automated testing.

**Comment by tanrak** [comment]
> I would like to give PHP 8.2 a try - @tanrak are you available for testing it a bit more thoroughly?

Sorry, i don't have much time at the moment. But as soon as I get around to it, i will report back here.

> If not, then I'll just keep 8.1 until I found a way to do more extensive automated testing.

That would certainly be the more sensible option. Especially as the version 8.1 is still supported until November 2024.
