### ISSUE TITLE
Events not sending invites

### ISSUE THREAD

**Issue by PintjesB** [ckulka/baikal-docker#195]
Was hoping maybe someone here has found a solution? Seen as I'm using this docker... 
Thanks in advance!

sabre-io/Baikal#1265

**Comment by ckulka** [comment]
Hi @PintjesB,

Do you know if you can send emails from PHP?

I use the file cypress/fixtures/mail-test.php in this repository in my tests, you can copy that into your container, adjust change it to your email address, and verify if you get it.

I wonder if it's an issue with Baikal or your email configuration.
