### ISSUE TITLE
Update to Baikal 0.6.1

### ISSUE THREAD

**Issue by BobWs** [ckulka/baikal-docker#20]
Hi,
Do you have plans to update the images to the latest baikal release 0.6.1?
https://github.com/sabre-io/Baikal/releases

Looking forward to it

**Comment by ckulka** [comment]
Hi @BobWs, release 0.6.1 should now be available with the `0.6.1` tags (incl. the Apache and nginx variants)

/close

**Comment by BobWs** [comment]
Thanks! I Will give it a try
