### ISSUE TITLE
Fatal Error: The system temp directory is not writeable

### ISSUE THREAD

**Issue by Dark-Gizmoa** [ckulka/baikal-docker#200]
After an automativ update with watchtower i get the error message "Baikal Fatal Error: The system temp directory is not writeable" when i try to connect to the WebUI.

Tests i did:
- delete of docker/baikal folder (backup is existent)
- delete of downloaded image
- recreation (checked that i cchown'ed the folders)
- chmod 777 for the complete fodler structure in my docker folder

Error message is still there

**Comment by Dark-Gizmoa** [comment]
after some testing:

docker exec -it <container_name> bash
  - touch /var/www/baikal/Specific/test.txt; mkdir /var/www/baikal/Specific/test-folder, touch /var/www/baikal/Specific/db/test.txt is possible without error

Docker Folder (inside container) /tmp is owned by root, only read rights for user nginx. After i fiddled a little bit with the rights (chmod 777), Baikal is up and running.

Is it possible to include a script (like /docker-entrypoint.d/40-fix-baikal-file-permissions.sh) to check the tmp folder and set permissions?

**Comment by ckulka** [comment]
Hi @Dark-Gizmoa , that is very strange... can you show me what you see when you run the following command inside the container:

```sh
ls -l / | grep tmp
```

Reason why I'm asking is because when I start a new ckulka/baikal:nginx container, the `/tmp` directory is owned by root, but also **is** writable by anyone:

```plaintext
$ docker run --rm -it ckulka/baikal:nginx ls -l / | grep tmp
drwxrwxrwt   2 root root 4096 Jun 12 00:00 tmp
```

**Comment by Dark-Gizmoa** [comment]
Hi @ckulka,

i think i found the failure:

I changed the image/container folder of docker to an external hdd.
Seems that the Access rights werde Set faulty (some correct with r/w some only r)
After i chowned the parent folder (in my case /sda/docker_internal/...) everything works fine
