### ISSUE TITLE
Update to Baikal 0.7.0

### ISSUE THREAD

**Issue by n-rodriguez** [ckulka/baikal-docker#22]
Hi,

Do you have plans to update the images to the latest baikal release 0.7.0?
https://github.com/sabre-io/Baikal/releases

Looking forward to it

**Comment by ckulka** [comment]
Hi @n-rodriguez,

I just pushed an update to Baikal 0.7.0 and PHP 7.4 to `ckulka/baikal:experimental`, `ckulka/baikal:experimental-apache` and `ckulka/baikal:experimental-nginx`.

Since I no longer run Baikal, could you please give it a run and see if it works for you?

If it does't, I'll create the `0.7.0` Docker images and push them to `latest` as well.

**Comment by BobWs** [comment]
> Hi,
> 
> Do you have plans to update the images to the latest baikal release 0.7.0?
> https://github.com/sabre-io/Baikal/releases
> 
> Looking forward to it

Did you by any chance installed the updated image? So is it working for you? 
I would like to update mine as well to the latest, but I don't want to mess up the stable setup that is running now in a production environment.

Could you please share your experience?

**Comment by ckulka** [comment]
Hi @BobWs,

I hope you meant @n-rodriguez - I unfortunately cannot test it myself because I don't have an instance that's currently up and running.

We _could_ set up a Google Hangouts/Slack/whatever to do it together on Thursday or next weekend though.

**Comment by BobWs** [comment]
> Hi @BobWs,
> 
> I hope you meant @n-rodriguez - I unfortunately cannot test it myself because I don't have an instance that's currently up and running.
> 
> We _could_ set up a Google Hangouts/Slack/whatever to do it together on Thursday or next weekend though.

Yes sorry I was talking to @n-rodriguez. 
But if you need someone to test the experimental image I could help. I have a VM docker were I’m able to do some testing.

**Comment by n-rodriguez** [comment]
@ckulka it seems that the image upgrade has failed :

```sh
root@cloud:/data/www/baikal docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                  NAMES
0ebdac237137        ckulka/baikal:experimental-nginx   "/bin/sh -c '/etc/in…"   4 minutes ago       Up 4 minutes        0.0.0.0:8800->80/tcp   calendar-exp.service
root@cloud:/data/www/baikal docker-enter 0ebdac237137
root@calendar:/# grep BAIKAL_VERSION /var/www/baikal/Core/Distrib.php 
define("BAIKAL_VERSION", "0.6.1");
```

**Comment by BobWs** [comment]
> @ckulka it seems that the image upgrade has failed :
> 
> ```shell
> root@cloud:/data/www/baikal docker ps
> CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                  NAMES
> 0ebdac237137        ckulka/baikal:experimental-nginx   "/bin/sh -c '/etc/in…"   4 minutes ago       Up 4 minutes        0.0.0.0:8800->80/tcp   calendar-exp.service
> root@cloud:/data/www/baikal docker-enter 0ebdac237137
> root@calendar:/# grep BAIKAL_VERSION /var/www/baikal/Core/Distrib.php 
> define("BAIKAL_VERSION", "0.6.1");
> ```

Did you specify and mount the config folder? That is new in 7.0

I have test `ckulka/baikal:experimental-apache` and it is working fine for me!

**Comment by BobWs** [comment]
I can confirm that `ckulka/baikal:experimental-apache` is working for me. 
If you push the official images I can give it another testrun!

**Comment by n-rodriguez** [comment]
@BobWs 

> Did you specify and mount the config folder? That is new in 7.0

yes

```sh
#!/bin/bash

docker run --name "calendar-exp.service" \
    --privileged=true \
    -h "calendar" \
    -v "$(pwd)/config":"/var/www/baikal/Specific" \
    -p "8800:80" \
    -d "ckulka/baikal:experimental-nginx"
```

**Comment by n-rodriguez** [comment]
But I still don't understand why the version is wrong within the container : 

```sh
root@calendar:/# grep BAIKAL_VERSION /var/www/baikal/Core/Distrib.php 
define("BAIKAL_VERSION", "0.6.1");
```

**Comment by BobWs** [comment]
@n-rodriguez Did you run the installer after updating your image?
After updating the container you need to login on the Baikal adminwebpage and finish the installation.

Also you need to specify the `config folder ` `--volume /volume1/docker/baikal/config:/var/www/baikal/config/ \ `

This is my setup maybe it could help you solve your problem!

```
docker pull ckulka/baikal:experimental-apache
docker stop baikal
docker rm baikal
docker run -it \
 --name baikal \
 --volume /volume1/docker/baikal/Specific:/var/www/baikal/Specific/ \
 --volume /volume1/docker/baikal/config:/var/www/baikal/config/ \
 --volume /volume1/documents/ssl/privkey.pem:/etc/ssl/private/baikal.private.pem:ro \
 --volume /volume1/documents/ssl/cert.pem:/etc/ssl/private/baikal.public.pem:ro \
 --volume /etc/localtime:/etc/localtime:ro \
 --volume /etc/TZ:/etc/timezone:ro \
 -p 8008:80 -p 8443:443 \
 --link mariadb:baikal-db \
 --env TZ='your/timezone' \
 --env BAIKAL_SERVERNAME='dav.youdomain.me' \
 --restart always ckulka/baikal:experimental-apache
```

**Comment by ckulka** [comment]
Sorry, oversight on my part: the `nginx` builds failed and didn't notice it. I fixed the issue (and it also published it now on Docker Hub).

Can you please give it another try?

One potential issue are the file permissions of `/var/www/baikal/config` when mounted into the container. I might add a `chmod` on container start (same as the `Specific` folder) before releasing it as `latest`.

**Comment by n-rodriguez** [comment]
> Can you please give it another try?

It works! The migration went fine :) Thank you!

**Comment by ckulka** [comment]
Thanks everyone for testing!

I've created the 0.7.0 tag and Docker Hub is now building it. It will take a few hours, my guess is around 3h.

**Comment by n-rodriguez** [comment]
@ckulka thank you!
