### ISSUE TITLE
Tag shows version 0.7.1. but image is missing from docker hub

### ISSUE THREAD

**Issue by BobWs** [ckulka/baikal-docker#24]
Hi,
Your Tags are showing you updated to version 0.7.1 but I cannot find the image in docker hub.
Are you still building the images?

**Comment by ckulka** [comment]
Huh... might be embarrassing, I forgot to pushed to master for the `exeperimental` tag and then forgot to push the tag `0.7.1` tag from my laptop to Github.

That's also why it didn't show up on the Github releases page (https://github.com/ckulka/baikal-docker/releases) until now, yet has an age of 24 days. Anyway, pushed it now and it's building... should be there by tomorrow.

**Comment by BobWs** [comment]
No problem! Could happen no worries m8! 😉

**Comment by BobWs** [comment]
Thanks it works! Updated to 0.7.1
