### ISSUE TITLE
exposed volume ownership

### ISSUE THREAD

**Issue by 917huB** [ckulka/baikal-docker#29]
Thanks for this great container, can I check something as I suspect this might be a bug but could also be user-error as I'm new to docker, bear with me please. 

When I expose a single volume as part of my docker run by adding `-v /var/lib/baikal-data/data:/var/www/baikal/Specific \` the config folder isnt saved to the persistent storage so each time i start the container I have to go back through configuration. 

I solved this by mounting the two folders to my peristent storage, ie.

```
            docker run blah blah network stuff here...
            -v /var/lib/baikal-data/data:/var/www/baikal/Specific \
            -v /var/lib/baikal-data/config:/var/www/baikal/config \
            ckulka/baikal:0.7.2-nginx-amd64
```

This solved the storage f the cnfig.yaml file, but the config folder is mounted as root, not as user 101 so throw an error when running. 

```
drwxr-xr-x 2 root root 4096 Nov  6 22:12 config
drwxr-xr-x 2  101  101 4096 Nov  6 22:14 data
```

Chown 101:101 config solved it (so far) but wondered if this is a bug, or if Ive made a newb error. 

thanks again

**Comment by ckulka** [comment]
Hi @917huB ,

thanks for writing - yes, this is a mistake in the example Docker Compose files!

I think the `config` folder was introduced in version 0.7.0 and I didn't update the examples. Thanks for letting me know, I'm not running Baikal myself anymore so I would not have noticed it.

**Comment by 917huB** [comment]
Thanks for confirming, if you are able to provide a patch I'm happy to test/confirm functionality. 
Also curious to hear what Cal/CardDAV system you are using post Baikal. 
FYI, I'm also fighting with some CORS issues on CardDAV sync only due to the presence of the If-Match directive. I'll dig in deeper to try and understand why it only affects carddav syncing but I dont think It should be an issue as I'm not cross origin (AFAIK!)

**Comment by ckulka** [comment]
So I was only half right: the one example file I checked had a mistake (typo in the path), but I think your issue does not come from that.

Can you please try this here:

```bash
# Prepare the local folders
cd /var/lib/baikal-data
mkdir -p data/db config
chown -R 101:101 config data 

# Start Baikal
docker run (...)
docker-compose up
```

If this works, then it comes Baikal trying to create files & folders but the local file permissions didn't allow the Nginx user (101) to do so. I also found out that the `db` folder has to be created manually, as Baikal doesn't create it on its own.

I hope this fixes your issue - btw, I also added this scenario with instructions as [docker-compose.localvolumes.yaml](https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.localvolumes.yaml) and made a note for it in the README.

Regarding CORS, that's sad to hear. I personally would actually like to take it out, but it's in there to address another issue. If you're stuck, shoot me the details, maybe I can help out.

Regarding my post-Baikal life... I have to admit that I moved everything over to Google. I went through a couple of devices in a relative short time and did not spend the time figuring out how to make it work everywhere. You could say I gave in on the temptation of an easy life 😞 Still feel bad about it, but not enough to set it up again for all devices.

**Comment by Drudoo** [comment]
@ckulka this worked for me.

I upgraded to 0.7.2 from 0.6.x by adding:

    volumes:
      - ./config:/var/www/baikal/config

to my docker-compose file. Then running `chown -R 101:101 config data` before using `docker-compose up`. Migration worked and permissions were set correctly.

**Comment by ckulka** [comment]
Good to hear! I'll close this issue then 👍
