### ISSUE TITLE
[Question] Is this a typo?

### ISSUE THREAD

**Issue by BobWs** [ckulka/baikal-docker#30]
Hi,
I've updated my docker container to the latest image, but I have noticed this in portainer. Is this a typo?
When login to Baikal Web Admin it shows the latest version 8.0 so my container is updated just fine.

![Screen_Shot](https://user-images.githubusercontent.com/5485820/107346978-a092aa00-6ac5-11eb-9b9c-e287a4d793db.png)

**Comment by ckulka** [comment]
Hey there, just checked the image tags, but they all show version 0.8.0.

I'm wondering where this comes from... can you run `docker inspect <image>` on the machine where the container runs and show the output?

**Comment by BobWs** [comment]
> Hey there, just checked the image tags, but they all show version 0.8.0.
> 
> I'm wondering where this comes from... can you run `docker inspect <image>` on the machine where the container runs and show the output?

This is part of the output:

```       
     "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
            "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
            "PHP_LDFLAGS=-Wl,-O1 -pie",
            "GPG_KEYS=42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF815FC910DEB46F53EA312",
            "PHP_VERSION=7.4.12",
            "PHP_URL=https://www.php.net/distributions/php-7.4.12.tar.xz",
            "PHP_ASC_URL=https://www.php.net/distributions/php-7.4.12.tar.xz.asc",
            "PHP_SHA256=e82d2bcead05255f6b7d2ff4e2561bc334204955820cabc2457b5239fde96b76",
            "PHP_MD5="
        ],
        "ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
        "Hostname": "baikal",
        "Image": "ckulka/baikal:latest",
        "Labels": {
            "description": "Baikal is a Cal and CardDAV server, based on sabre/dav, that includes an administrative interface for easy management.",
            "repository": "https://github.com/ckulka/baikal-docker",
            "version": "0.7.2",
            "website": "http://sabre.io/baikal/"
        },
        "OnBuild": null,
        "OpenStdin": true,
        "StdinOnce": true,
        "StopSignal": "SIGWINCH",
        "Tty": true,
        "User": "",
        "Volumes": {
            "/etc/localtime": {},
            "/etc/ssl/private/baikal.private.pem": {},
            "/etc/ssl/private/baikal.public.pem": {},
            "/etc/timezone": {},
            "/var/www/baikal/Specific": {},
            "/var/www/baikal/config": {}
        },
        "WorkingDir": "/var/www/html"
    },
    "Created": "2021-02-02T07:26:13.078447702Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
```


![FFF2D8E8-042C-4380-854D-B6B3D762D36C](https://user-images.githubusercontent.com/5485820/107971263-8cade300-6fb2-11eb-8f5c-40ef81c5c4ab.jpeg)

**Comment by BobWs** [comment]
Turns out that it isn't a typo or bug on your side! The problem is with Portainer, when I use Portainer to update a container then the information like labels is not updated properly. The container itself does get updated. 

So I think it is a bug from portainer.

![Screen_Shot](https://user-images.githubusercontent.com/5485820/108054939-9a657600-704f-11eb-9d41-18ccdb8520c6.png)
