### ISSUE TITLE
405 when trying to access call dav w/IOS14

### ISSUE THREAD

**Issue by smaktacular** [ckulka/baikal-docker#37]
When trying to setup caldav sync on IOS 14.5.1 I get the following log output:

192.168.208.9 - - [13/May/2021:19:49:50 +0000] "PROPFIND /.well-known/caldav HTTP/1.1" 302 145 "-" "iOS/14.5.1 (18E212) dataaccessd/1.0" "192.168.1.117"

192.168.208.9 - - [13/May/2021:19:49:50 +0000] "PROPFIND / HTTP/1.1" 405 157 "-" "iOS/14.5.1 (18E212) dataaccessd/1.0" "192.168.1.117"  

192.168.208.9 - - [13/May/2021:19:49:50 +0000] "PROPFIND /principals/ HTTP/1.1" 405 157 "-" "iOS/14.5.1 (18E212) dataaccessd/1.0" "192.168.1.117"

192.168.208.9 - - [13/May/2021:19:49:50 +0000] "PROPFIND /calendar/dav/username/user/ HTTP/1.1" 405 157 "-" "iOS/14.5.1 (18E212) dataaccessd/1.0" "192.168.1.117"

Container (0.8.0 nginx) runs behind traefik with self-signed cert and card dav is working fine. Also the CA that issued the cert is trusted by IOS.

**Comment by ckulka** [comment]
Sounds suspiciously like this one here: <https://github.com/sabre-io/Baikal/issues/1030>

Can you give it a try and see if that resolves it?

**Comment by smaktacular** [comment]
Actually I had to add the following to the container config of traefik:

```
    - "traefik.http.middlewares.baikal-dav.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.baikal-dav.redirectregex.replacement=https://$$1/dav.php/"
      - "traefik.http.middlewares.baikal-dav.redirectregex.permanent=true"
      - "traefik.http.routers.baikal.middlewares=baikal-dav"
```

I'm not 100% sure why this needs to be on rev proxy side instead of nginx, but anyways ...

**Comment by ckulka** [comment]
Hi @smaktacular ,

I don't have an iPhone, could you please try to use (e.g. mount) a modified Nginx file works in iOS and the other devices/apps you are using?

I'd be curious to know if adding a trailing slash `/` to line 10 and 11 in `/etc/nginx/conf.d/default.conf` resolves it (since that's the only difference in the Traefik configuration you posted):

```nginx
  rewrite ^/.well-known/caldav /dav.php/ redirect;
  rewrite ^/.well-known/carddav /dav.php/ redirect;
```

Baikal's documentation doesn't have it, but this might just be an oversight.

**Comment by smaktacular** [comment]
@ckulka: Did the test and the only difference it made was that the uri entered in the ios setup dialog recieved the trailing slash as well. Still 405 without the modification to the traefik labels

**Comment by smaktacular** [comment]
And, on top to see a difference in both configs, you one needs to setup the account from scratch, because once the account is setup properly you can remove the rev proxy directives and everything still works. But if you set the account up without the rev proxy directives it will not work, even with the trailing slah addition, suggested by @ckulka .

**Comment by ckulka** [comment]
Thanks for your PR! I merged it and will close this issue as this is now fixed.

**Comment by lohrbini** [comment]
Hey 👋 
for me it works like a charm with all iOS devices (Mac, iPhone). Maybe this could solve issue:

- https://github.com/tchapi/davis/issues/182
