### ISSUE TITLE
On Ubuntu: Permission denied to create file (filename ....ics) in /var/www/baikal/vendor/sabre/dav/lib/DAV/Collection.php:92

### ISSUE THREAD

**Issue by dansan** [ckulka/baikal-docker#42]
When the current Docker image `ckulka/baikal:nginx` ist started on Ubuntu 20.04 (focal) system, users accounts and calendars can be created, but no events can be written.
It seems to work without problems on Mac OS X.
I tried on a remote Ubuntu server `Ubuntu 20.04.2 LTS` and on my notebook running a Ubuntu derivative (`Linux Mint 20.1`).

On the Ubuntu server the Docker container is started with:
```
/usr/bin/docker run --rm -p 8800:80 -v /var/lib/baikal-calendar/Specific:/var/www/baikal/Specific -v /var/lib/baikal-calendar/config:/var/www/baikal/config --name calendar ckulka/baikal:nginx
```

On the notebook it is started exactly like on the Github page written (but with an unprivileged port):
```
docker run --rm -it -p 8800:80 ckulka/baikal:nginx
```

On both I get:
```
2021/06/18 13:38:56 [error] 19#19: *243 FastCGI sent in stderr: "PHP message: LogicException: Requested uri (/dav.php?sabreAction=plugins) is out of base uri (/dav.php/) in /var/www/baikal/vendor/sabre/http/lib/Request.php:184
Stack trace:
#0 /var/www/baikal/vendor/sabre/dav/lib/DAVACL/Plugin.php(832): Sabre\HTTP\Request->getPath()
#1 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAVACL\Plugin->beforeMethod()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#4 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(321): Sabre\DAV\Server->start()
#5 /var/www/baikal/Core/Frameworks/Baikal/Core/Server.php(119): Sabre\DAV\Server->exec()
#6 /var/www/baikal/html/dav.php(69): Baikal\Core\Server->start()
#7 {main}" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /dav.php?sabreAction=plugins HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "my.fq.dn", referrer: "https://my.fq.dn/dav.php"
```

Platform infos:
```
# docker --version
Docker version 20.10.7, build f0df350

# uname -a
Linux my.fq.dn 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
# docker --version
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2

# uname -a
Linux sommar 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
# docker inspect ckulka/baikal:nginx
[
    {
        "Id": "sha256:b6f8f7ad6d4e615138baa26747b3239625147cd51b6182c60b0cedb70db9464f",
        "RepoTags": [
            "ckulka/baikal:nginx"
        ],
        "RepoDigests": [
            "ckulka/baikal@sha256:58a25d769ed4a044d7ed4a2c776f0d969d2491725626a21ccbfd49afdd68df3f"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-01-26T23:15:49.392153549Z",
        "Container": "71f645c93ea715c3972911751eb420aa4a0b3c275f10435600cab280d8293127",
....
```

I'd appreciate help setting this up on an Ubuntu or Debian server.
I can edit code if adding debug statements is of help to find the problem cause.

**Comment by ckulka** [comment]
Hi @dansan, sorry for the late reply, I'm guessing this is already a non-issue by now or (worse) you moved on.

Regardless, trying my luck or for future reference: I interpret the error message

```
Requested uri (/dav.php?sabreAction=plugins) is out of base uri (/dav.php/)
```

as nothing to do with the image or your OS, but rather that the client sends a different HTTP request. When connecting it to your MacOS container, the slash between `/dav.php` and `?sabreAction=plugins` exists. When connecting to your Ubuntu containers, the slash was missing.

If the client configuration was exactly the same it might be something else, but that'd be my first simple guess.

If that wasn't it, can you please check if the Docker images are the same (i.e. have the same id)? I'd like to rule out that it's a regression in one of the older or newer images.

**Comment by dansan** [comment]
Hello @ckulka, the problem has been resolved. It was done during my absence, so I'm not sure if anything was done on the server. From what I understood, the problem was with the client using the wrong URL.
Sorry for not closing the issue sooner. The customer is very happy with Baikal :)
