### ISSUE TITLE
Unraid Installation Guide - Wiki creation for links?

### ISSUE THREAD

**Issue by Joshndroid** [ckulka/baikal-docker#43]
Hello.
I came across your program while initially searching for a lightweight caldav to replace nextcloud.

I have setup your Baikal docker to run within unraid and utilising a separate mysql database (not that the external database was necessary).
I utilise Unraid as my main server PC as many others do out there.
If you have not heard of Unraid before - https://unraid.net/
Unraid community apps - https://unraid.net/community/apps

At present I have written a bit of a guide for others out there who wish to give this a whirl. I will post it here as you dont have a wiki setup where I can post it in there. I was potentially going to submit a community apps version compatible to make the process a bit easier for others but may leave mine to run for a while longer before I jump to that.

If possible, could you start a wiki that I could post the guide to and potentially allow it to be linked to to the installation section of your readme?

Here is what I have working within my setup thus far;

Baikal – Unraid Docker Installation

This Unraid Docker Installation guide will mostly assume a few things;
1.	You have docker enabled within Unraid
2.	You have enabled community apps within Unraid
3.	You have enabled within settings the ability to utilize dockerhub for search results (see settings within apps tab)
4.	OPTIONAL - You have a reverse proxy container and network to allow for certificate handling & SSL connections
Installation Note – You can change the tag within the repo in the later steps to one that is suitable for your setup. See here for further https://github.com/ckulka/baikal-docker
Further installation Note – If you’re choosing to utilise an external database such as mariadb, please ensure that you set this up correctly in that a database and user are all created as well as the network both Baikal and the mysql database are on in order for Baikal to connect and function correctly.
With that in mind, the installation of Baikal is rather simple once you have the above setup.
5.	Head over to apps and search for Baikal
6.	Click to begin the installation of Baikal within the search result. (The repo is ckulka/baikal)
7.	Set the toggle on the right in the template as ‘advanced view’ (It defaults to basic view)
8.	Check that your satified with the tag that is being placed within your docker repo line to ensure your pulling the right version that you want. See here for further tags and their update history https://hub.docker.com/r/ckulka/baikal/tags?page=1&ordering=last_updated
9.	Set your ‘Icon URL’ as https://github.com/sabre-io/sabre.io/blob/master/source/img/baikal.png?raw=true (This will provide you with the Baikal logo)
10.	Set your ‘WebUI’ as http://[IP]:[PORT:80]/ (This could be changed to whatever suits your local server port requirements - see below)
11.	Set ‘Extra Parameters’ as --restart=always
12.	Set your network type as needed (OPTIONAL - Set network type as your network that you utilize for your SSL certs (for me its proxnetwork).)
13.	Add in your static IP address that you will utilize for Baikal. (It makes it easier to get to your hosted instance)
14.	Add in a ‘path’ as;
•	Name – Config
•	Container Path - /var/www/baikal/config
•	Host Path - /mnt/user/appdata/baikal/config (this could be changed to whatever suits your local server path requirements if your appdata path is different)
•	Default Value - /mnt/user/appdata/baikal/config (see above)
•	Acccess Mode – Read/Write
•	Description – Container Path: /var/www/baikal/config
15.	Add in a ‘path’ as;
•	Name – Specific
•	Container Path - /var/www/baikal/Specific
•	Host Path - /mnt/user/appdata/baikal/specific (this could be changed to whatever suits your local server path requirements if your appdata path is different)
•	Default Value - /mnt/user/appdata/baikal/specific (see above)
•	Acccess Mode – Read/Write
•	Description – Container Path: /var/www/baikal/Specific
16.	Now add in a ‘port’ as;
•	Name – Port
•	Container Port – 80
•	Host Port – 80 (this could be changed to whatever suits your local server port requirements if your 80 is already in use)
•	Default Value – 80 (this could be changed to whatever suits your local server port requirements - as above)
•	Connection Type – TCP
•	Description – Container Port: 80
17.	Click apply to download/install the container.
20.	Start your Baikal docker container
21.	OPTIONAL – Head over to your SSL cert provider container of choice and set-up as necessary to server certs to your Baikal instance for your domain.
22.	Head over to your webUI or domain and start the admin creation process.
23.	You have the choice within the steps to utilise the sqlite database or an external mysql (such as mariadb). Just make sure your mysql database is on the same network as your Baikal server so you can easily access it. If your choosing to go the mysql method like I did you will need to conduct further setup within the mysql docker/installation in order for Baikal to function correctly.

**Comment by ckulka** [comment]
Hi @Joshndroid, thanks for the guide! I looked into the wiki settings and unfortunately I can't seem to set up the permissions that way. Organisations might be able to do this, but this is a user account repo.

Instead, could you please submit a PR and add the guide to `docs/Unraid-Installation-Guide.md` (or something along those lines in the new `docs` folder)?

I can then publish it using Github pages and also allow others to contribute more pages. I'll of course still link it in the `README.md` if that's not in your PR yet :)

Or feel free to let me know when you're happy with your guide here and I'll publish it there while setting up Github pages, whichever works better for you.

Thanks again for contributing!

**Comment by ckulka** [comment]
Merged and published: <https://ckulka.github.io/baikal-docker/docs/unraid-installation-guide.html>

Thanks again @Joshndroid !
