### ISSUE TITLE
Baikal does not work anymore in latest containers

### ISSUE THREAD

**Issue by therealprof** [ckulka/baikal-docker#5]
PHP was obviously automatically upgraded to 7.2 in latest builds but Baikal is not compatible with that version anymore due to the use of deprecated functions.

Pinning the used php container to 7.0 for instance works until the Baikal project decides to address https://github.com/sabre-io/Baikal/issues/711 . I'd be happy to submit a PR for this but it's probably faster to simply add 3 characters to the Dockerfile. ;)

**Comment by Bajista58** [comment]
Would you please explain what 3 characters I should add then please? I'm trying to set this up but facing issues due to php version

**Comment by therealprof** [comment]
@Bajista58 Open the `Dockerfile` and change the beginning of the file to:
```
# Set the base image
FROM php:7.0-apache
```

**Comment by ckulka** [comment]
@therealprof @Bajista58 only saw it now, sorry ... had notifications turned off.

Thanks for the suggested fix, I changed the base image to `php:7.0-apache` and it runs smooth again. So far only `latest` and `0.4.6` tags are fixed, older versions will be updated if anyone actually needs them.
