### ISSUE TITLE
baikal docker for synology diskstation

### ISSUE THREAD

**Issue by nillebor** [ckulka/baikal-docker#69]
i have been using the baikal server for many years.
i use this on a diskstation with intel processor.
unfortunately, your docler package does not work, you receive the error message "Function not implemented: AH00141: Could not initialize random number generator"
could it be because the i386 (x86) is currently not supported?

could you offer the support, because I use several dockerfiles and the administration would be easier.

**Comment by ckulka** [comment]
I'll try to add an image for the `386` platform and write when it's available as an experimental build - can you then give it a try?

**Comment by ckulka** [comment]
Hi @nillebor , the version 0.9.1 images should now support the i386 platform - can you give them a try and see if your error goes away?

**Comment by nillebor** [comment]
thx i will test it!
an extra image? or available in th  :lastest image?s' not an extra image? or available in th  :lastest image?
I see no x86 until now

I'll see tomorrow or the day after once again

**Comment by ckulka** [comment]
For now you can use any of the experimental tags (<https://hub.docker.com/r/ckulka/baikal/tags?page=1&name=experimental>), e.g.

* `ckulka/baikal:experimental` or `ckulka/baikal:experimental-apache`
* `ckulka/baikal:experimental-nginx`

Once I know they are working I release them und `latest` etc.

**Comment by nillebor** [comment]
I've tried the 3 containers. unfortunately, it is under the apache is not possible, the container is always terminated immediately with the error message: 
`Function` not implemented: AH00141: Could not initialize random number generator". the error is also true for the files: experimental and experimental_apache!

the experimental nginx, it is already better. there contäiner starts. Website is reachable, the password can be velocity. because the error messages come see screenshot. 
![Screenshot 2022-01-22 at 18-45-32 Baïkal Maintainance](https://user-images.githubusercontent.com/59985723/150650432-47f51e85-9071-414f-b16c-4d5418e7e9a2.png)

after create db-folder ind /specific the following error is coming::
`Exception: Fatal error: no connection to a database is available. in /var/www/baikal/Core/Frameworks/Baikal/Core/Tools.php:71
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Framework.php(72): Baikal\Core\Tools::assertBaikalIsOk()
#1 /var/www/baikal/Core/Frameworks/BaikalAdmin/Framework.php(34): Baikal\Framework::bootstrap()
#2 /var/www/baikal/html/index.php(52): BaikalAdmin\Framework::bootstrap()
#3 {main}`

currently I use apache 2.4 & php 7.4 natively on the diskstation, so without docker. eventually, the Yes you can help or can tell me where the error is or what is missing

**Comment by nillebor** [comment]
hello kulka

I want to give a brief info - Baikal Docker on the Diskstation works fine. thanks for that.

i only have one x86/i386 diskstation, so I can't say anything about a modern x64 diskstation.

I tested the following versions: 

- baikal 0.9.1 Apache - don't work: `(38)Function not implemented: AH00141: Could not initialize random number generator`
- baikal 0.9.1 Apache-php_8.0 - don't work; `(38)Function not implemented: AH00141: Could not initialize random number generator`
- baikal 0.9.1 nginx - works fine
- baikal 0.9.1 nginx-php_8.0 - works fine

if I saw this correctly, is php8.1 installed in the Apache & nginx version? I'm sticking with nginx with php_8.1.

Can you also offer a "latest version" for nginx that makes it easier to update?

Do you have any information about what the error can be with apache?does the error message tell you anything?
I have written a tutorial in the German Synology Forum where I have already written your work!

Please continue and maybe they will make a "latest" Nginx version ;)

many thx

**Comment by ckulka** [comment]
Thanks for the update! Glad Nginx is working out.

> Do you have any information about what the error can be with apache?does the error message tell you anything?
I have written a tutorial in the Synology Forum where I have already written your work!

I was looking around more, looks like quite a lot of people have the AH00141 error with Synology, e.g. https://github.com/bitnami/bitnami-docker-apache/issues/106 and https://github.com/nextcloud/docker/issues/1574. From what I'm reading, it's due to the kernel version that's missing components required by Apache. You'd normally fix this by updating the kernel, but apparently no updates are available by Synology.

One of the issues mention an escape hatch: build the Apache image with an older base image, which I could release as it's own variant, similar to what I did with the PHP 8.0 and 8.1 image variants. It'll make things slightly more confusing because of the inflation of image variants, but it could be a way out. 

But since Nginx seems to work: unless Nginx isn't viable for other reasons and Apache is a must, I'd like to keep things simple as they are now and stick to the latest versions... let me know what you think.

> if I saw this correctly, is php8.1 installed in the Apache & nginx version? I'm sticking with nginx with php_8.1.

Yes, the `nginx` image comes with PHP 8.1 and the `nginx-php8.0` one with PHP 8.0. Using PHP 8.1 (like you do) is the way to go 👍 There were a couple of issues opened here and over at the Baikal repository that were caused by the latest PHP version, so I released the PHP 8.0 image to fix them until Baikal fully supports PHP 8.1 for everyone.

> Can you also offer a "latest version" for nginx that makes it easier to update?

Can you elaborate? Not sure if I understand correctly, do you mean that the Nginx image should be `ckulka/baikal:latest` instead of `ckulka/baikal:nginx`?

**Comment by nillebor** [comment]
thank you for your great work.

The errors with Apache and Synology should not be a problem, because nginx works. The only funny thing is that the original DSM software is exactly the other way around. nginx does not work there and apache is absolutely necessary!

I can live with it well. Also php_8.1 works without problems - I love it - I'm really happy with it!

But I would like to find it if you would also offer a latest for nginx. because you could easily make an update and with wathtower even automatically, if desired. Is it possible or can you just always set a "latest" image with docker? so one latest for apache and one for nginx?

Please keep it up.
Thanks for your efforts on the apache bug

cheers

**Comment by ckulka** [comment]
Ah, I see what you mean and the good news is that it's already set up that way: the `nignx` image tag (and all others without version numbers for that matter) always contain the latest version of Baikal. In other words, using the `nginx` image and pulling it regularly will make sure you're always running the latest version of Baikal.

I didn't prefix it with `latest-` following the practice of other official Docker image naming conventions... if those are good is debatable though. Publishing `latest-nginx` as an alias for `nginx` is easy though, so if this makes it easier to understand I'm open to introducing it.

What is troubling is that `ckulka/baikal:0.9.1-nginx` works for you and `ckulka/baikal:nignx` doesn't, even though they are the same. You can look up the image ids on Docker Hub (<https://hub.docker.com/r/ckulka/baikal/tags?page=1&name=nginx>), "nignx" and "0.9.1-nginx" are exactly the same, e.g. `bbe8ae2ee84d` for i386.

Can you please run `docker images ckulka/baikal` and compare the image ids to make sure they are the same?

**Comment by nillebor** [comment]
nginx & 0.9.1-nginx works.here fin - no problem, all good :+1: )

the tag nginx to always get the latest version is completely sufficient, name adjustment is still not necessary. everything can remain as it is. my problems are completely solved the contribution can be closed.

please keep up the good work :+1:

**Comment by ckulka** [comment]
Thank you, appreciate the feedback, it's always nice to hear :)
