### ISSUE TITLE
iOS example with Traefik doesn't work using YAML

### ISSUE THREAD

**Issue by Drudoo** [ckulka/baikal-docker#70]
In the [example](https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.ssl.yaml) for using Traefik on iOS, the regex replacement uses double dollar signs. This works when using labels in the compose file, but not when using a YAML configuration file for Traefik. In the compose file, the dollar sign needs to be escaped, but in the YAML file, this isn't the case. 

Adding info to the compose example in the form of the following, would be beneficial: 

```
# Docker Compose file for a Baikal server with Let's Encrypt using Traefik (https://docs.traefik.io/)
#
.......
# 3. Start the stack: docker-compose -f docker-compose.ssl.yaml up
# 
# If using a traefik provider file in YAML or TOML, you do not need to escape characters. The regex should therefore be:
# redirectRegex:
#   replacement: "https://$1/dav/php/
# 
```

**Comment by ckulka** [comment]
Good idea @Drudoo, I added it to the example.
