### ISSUE TITLE
nginx container does not start if Docker IPv6 disabled

### ISSUE THREAD

**Issue by Aggtaa** [ckulka/baikal-docker#73]
NginX should not listen on IPv6 address by default as IPv6 can be disabled in docker settings globally or per container.

```
baikal_1  | 2022/01/30 10:25:53 [emerg] 18#18: socket() [::]:80 failed (97: Address family not supported by protocol)
baikal_1  | nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
```

Container does not start and there is no way to configure it as NginX is not set to react to any environment variable and NginX config is not exposed to host for edits.

**Comment by ckulka** [comment]
Hi @Aggtaa, thanks - I'll see if there's a way to have both given some need IPv6 and some don't.

Can you run the following commands inside the container and share the output?

```sh
cat /sys/module/ipv6/parameters/disable
cat /sys/module/ipv6/parameters/disable_ipv6
sysctl -a 2>/dev/null | grep disable_ipv6
```

If possible, can you also share the output of the same commands but with IPv6 enabled?
