### ISSUE TITLE
DB permissions

### ISSUE THREAD

**Issue by Lithimlin** [ckulka/baikal-docker#78]
I'm currently recreating my baikal setup because I did a fresh setup of my home server. Before taking the old one down, I made a backup of the calendar data and config. I've now copied the data into the new volumes/directories but the webpage tells me the following:
> DB file is not writable. Please give write permissions on file '/var/www/baikal/Specific/db/db.sqlite'

From my perspective, I can't find anything wrong with the permissions in- or outside of the container:
```console
$ ls -la baikal/data/
total 12
drwxr-xr-x 3 pi pi 4096 Mar 13 17:51 .
drwxr-xr-x 4 pi pi 4096 Mar 13 17:52 ..
drwxr-xr-x 2 pi pi 4096 Mar 13 17:51 db
-rw-r--r-- 1 pi pi    0 Mar 13 17:51 INSTALL_DISABLED

$ ls -la baikal/data/db/
total 264
drwxr-xr-x 2 pi pi   4096 Mar 13 17:51 .
drwxr-xr-x 3 pi pi   4096 Mar 13 17:51 ..
-rw-r--r-- 1 pi pi 262144 Mar 13 17:51 db.sqlite
-rw-r--r-- 1 pi pi      0 Mar 13 17:51 .empty

$ docker exec -it baikal /bin/bash
root@238a5b48ecf0:/# ls -la /var/www/baikal/Specific/
total 12
drwxr-xr-x 3  1000  1000 4096 Mar 13 17:51 .
drwxr-xr-x 1 nginx nginx 4096 Jan 26 22:57 ..
-rw-r--r-- 1  1000  1000    0 Mar 13 17:51 INSTALL_DISABLED
drwxr-xr-x 2  1000  1000 4096 Mar 13 17:51 db

root@238a5b48ecf0:/# ls -la /var/www/baikal/Specific/db
total 264
drwxr-xr-x 2 1000 1000   4096 Mar 13 17:51 .
drwxr-xr-x 3 1000 1000   4096 Mar 13 17:51 ..
-rw-r--r-- 1 1000 1000      0 Mar 13 17:51 .empty
-rw-r--r-- 1 1000 1000 262144 Mar 13 17:51 db.sqlite
```

Any ideas what could be going wrong here?

**Comment by mattmurr** [comment]
I've just run into this too, I believe everything should be owned by the user within the container.
See this link: https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.localvolumes.yaml

**Comment by Lithimlin** [comment]
Ah, I'd tried that before. Then the webpage told me the config.yaml could not be accessed.
However, that was because I had not correctly set the permissions for the `config` directory, only for the `Specific`
