### ISSUE TITLE
bump to 0.9.2 only experimaental

### ISSUE THREAD

**Issue by nillebor** [ckulka/baikal-docker#83]
no update for:
- latest
- apache
- apache+php8.0
- nginx
- nginx-php8.0

Update only for [all](https://hub.docker.com/r/ckulka/baikal/tags) experimental-Images
is it´s right?

**Comment by ckulka** [comment]
Yes, life interfered - I'm creating the release now and it should be there within the next hour or two.

**Comment by ckulka** [comment]
Building now, should be done in about 12 minutes: https://github.com/ckulka/baikal-docker/actions/runs/2105225521

**Comment by nillebor** [comment]
thank you works well :)
