### ISSUE TITLE
How to fix "Request entity too large" error

### ISSUE THREAD

**Issue by dbobak** [ckulka/baikal-docker#87]
When trying to add to calendar task with a large attachment, I'm getting error "Request entity too large". Running baikal:nginx image.
How to fix it?

**Comment by ckulka** [comment]
Hi @dbobak, you will need to update the `/etc/nginx/conf.d/default.conf` file inside the container and add [`client_max_body_size`](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) with a value larger than the biggest HTTP request you expect to upload:

```nginx
server {
  listen 80;
  # ...
  client_max_body_size 2M;
}
```

The probably easiest way is to use the [`files/nginx.conf` file from this repository](https://github.com/ckulka/baikal-docker/blob/master/nginx.dockerfile), modify it, and then mount it into the container.

Alternatively you can create a bash script that adds that line after (for example) the `listen 80;` line and mount it as `/docker-entrypoint.d/50-client_max_body_size.sh` inside the container. See [Insert line after match found](https://fabianlee.org/2018/10/28/linux-using-sed-to-insert-lines-before-or-after-a-match/) for pointers on how to do this. I prefer this method as you keep using the current nginx configuration file that comes with the container and won't be missing updates... but it's arguably more complicated.

Hope this helps 👍
