### ISSUE TITLE
Reinstall after previous install catch-22 : Mysql, Docker,/admin/install

### ISSUE THREAD

**Issue by mfabache** [ckulka/baikal-docker#89]
Not a bug, as I had this working before hand, but something wonky I am likely doing...

**Baikal version**: 0.x
Latest as of 08-May-22
docker image (via compose yml)

**Expected behaviour**:
To preform a fresh install and restart from scratch

**Current behaviour**:
I cannot reinstall the setup and get a 

> Installation was already completed. Please head to the admin interface to modify any settings.

Seems simple to fix, right?  I'm sure I have something wrong, but:
I've DESTROYED the database, I've destroyed docker (compose) image
I've CREATED a (new mysql) database for Baikal, I've tried to reinstall via the <host>/admin/install and get the message above

//edit: perhaps something is not lining up any more (via db) and escapes somewhere else???

**Steps t reproduce**:

1. Having a once pre-existing and working implementation
2. Lose the container (in some way, I'm not sure)
3. successfully recreate the container (of baikal) with a new database
4. launch the <host>/admin/install
5. receive 'Installation was already completed' message.  3rd base!

Best,
Michael

**Comment by ckulka** [comment]
Hi Michael,

can you share your `docker-compose.yaml`file (with redacted passwords)?

I don't know if you also use volumes, but I want to make sure that by "destroying" you also mean that you either deleted the volumes too or (if they are local folder mounts) removed the files inside them.

**Comment by mfabache** [comment]
Thanks Cyrill for looking into this.

Here is what I have for the yml


  baikal:
    image: ckulka/baikal:nginx
    restart: always
    container_name: baikal.DockerX
    networks:
    - dockerX_network
    links:
    - mariadb
    ports:
      - "8090:80"
    environment:
    - MYSQL_ROOT_PASSWORD=<redacted>
    - MYSQL_DATABASE=<redacted>
    - MYSQL_USER=<redacted>
    - MYSQL_HOST=<redacted>
#mff#    labels:
#mff#      traefik.enable: "true"
#mff#      traefik.frontend.rule: "Host:<redacted>"
#mff#      traefik.port: 80
#mff#      traefik.http.middlewares.baikal-dav.redirectregex.regex: "https://(.*)/.well-known/(card|cal)dav"
#mff#      traefik.http.middlewares.baikal-dav.redirectregex.replacement: "https://$$1/dav.php/"
#mff#      traefik.http.middlewares.baikal-dav.redirectregex.permanent: "true"
#mff#      traefik.http.routers.baikal.middlewares: "baikal-dav"

    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific

**Comment by ckulka** [comment]
Sorry for not following up - I'd imagine you have this solved by now, but if anyone coming across this: I suspect this is because the volumes were not deleted. So when you started a new container, then the old volumes with the old files (config and data) were still used.

To completely start from scratch, you'd also need to remove the volumes:

```sh
# Use Docker Compose to remove containers, networks, and volumes
docker-compose down --volumes

# Alternatively, use the Docker CLI to list volumes and delete them manually
docker volume ls
docker volume rm <volume name>
```
