### ISSUE TITLE
Email invites are not sent

### ISSUE THREAD

**Issue by raenrfm** [ckulka/baikal-docker#91]
I've installed Baikal on my vps running docker, I have a mail server set up in a different container on port 25 it works, I have the port allowed from the vps provider but baikal never sends out invites for events from Thunderbird.  There doesn't seem to be a lot of info on how this should be set up.  Can someone help me with this?

**Comment by throwaway876** [comment]
It has sendmail installed but after taking a brief look at the dockerfiles and such I don't see where it is configured using env vars or anything.

I'm thinking it simply isn't implemented yet. Note- this is something that this project will have to do separate sadly as the upstream is only concerned about the software itself and doesn't support docker outright. They basically leave email configuration up to whoever installs it.

**Comment by ckulka** [comment]
Hi @raenrfm,

Better late than never: This should be solved now with the second-last release, a guide on how to set it up is at [docs/email-guide.md](https://github.com/ckulka/baikal-docker/blob/master/docs/email-guide.md).
