### ISSUE TITLE
Allow configuring database via env variables for unattanded provisioning 

### ISSUE THREAD

**Issue by stavros-k** [ckulka/baikal-docker#95]
Instead of having to go through the setup on the first installation, have envr variables to define the required info, and run the setup on the first startup

Thanks!

**Comment by ckulka** [comment]
Hi @stavros-k,

I think there might already be a solution to this: the `baikal.yaml` file contains the fields that you set up in the initial wizard when Baikal starts for the first time. An example of this file with the fields available is in their repository: [sabre-io/Baikal: config/baikal.yaml.dist](https://github.com/sabre-io/Baikal/blob/master/config/baikal.yaml.dist).

If you need more fields, then I think this would be a request in the [sabre-io/Baikal](https://github.com/sabre-io/Baikal) repository, given this is something that'd need to be implemented in the Baikal code base.

Hope this helps, let me know if you meant something 👍
